// Code generated by core/cmd/fsapis. DO NOT EDIT.
//
// A typed client over the same Go types the handlers are written against.
// Compiles for GOOS=js too, where net/http is the browser's fetch().

package apiclient

import (
	"context"
	"github.com/mirairoad/guard/internal/telemetry/model"
	"github.com/mirairoad/guard/server/apis/contract"
	"github.com/mirairoad/howl-go/core/api"
)

// Client calls the API. An empty base URL means same origin, which is what
// a page running in the browser wants.
type Client struct{ *api.Transport }

func New(baseURL string) *Client { return &Client{Transport: api.NewTransport(baseURL)} }

// CreateView calls POST /api/views.
func (c *Client) CreateView(ctx context.Context, body model.View) (model.View, error) {
	return api.Call[model.View](ctx, c.Transport, "POST", "/api/views", nil, body)
}

// DeleteView calls DELETE /api/views/{id}.
func (c *Client) DeleteView(ctx context.Context, id string) error {
	_, err := api.Call[api.None](ctx, c.Transport, "DELETE", api.Path("/api/views/{id}", id), nil, nil)
	return err
}

// Event calls GET /api/events/{id}.
func (c *Client) Event(ctx context.Context, id string) (model.Event, error) {
	return api.Call[model.Event](ctx, c.Transport, "GET", api.Path("/api/events/{id}", id), nil, nil)
}

// Events calls GET /api/events.
func (c *Client) Events(ctx context.Context, query model.Filter) ([]model.Event, error) {
	return api.Call[[]model.Event](ctx, c.Transport, "GET", "/api/events", query, nil)
}

// Facets calls GET /api/facets.
func (c *Client) Facets(ctx context.Context) (model.Facets, error) {
	return api.Call[model.Facets](ctx, c.Transport, "GET", "/api/facets", nil, nil)
}

// Health calls GET /healthz.
func (c *Client) Health(ctx context.Context) (contract.Health, error) {
	return api.Call[contract.Health](ctx, c.Transport, "GET", "/healthz", nil, nil)
}

// Logs calls GET /api/logs.
func (c *Client) Logs(ctx context.Context, query model.Filter) ([]model.Event, error) {
	return api.Call[[]model.Event](ctx, c.Transport, "GET", "/api/logs", query, nil)
}

// MetricSeries calls GET /api/metrics/series.
func (c *Client) MetricSeries(ctx context.Context, query contract.SeriesQuery) ([]model.MetricSeries, error) {
	return api.Call[[]model.MetricSeries](ctx, c.Transport, "GET", "/api/metrics/series", query, nil)
}

// PreviewView calls POST /api/views/preview.
func (c *Client) PreviewView(ctx context.Context, body contract.PreviewRequest) (model.Frame, error) {
	return api.Call[model.Frame](ctx, c.Transport, "POST", "/api/views/preview", nil, body)
}

// Purge calls POST /api/settings/purge.
func (c *Client) Purge(ctx context.Context) (contract.Purged, error) {
	return api.Call[contract.Purged](ctx, c.Transport, "POST", "/api/settings/purge", nil, nil)
}

// Settings calls GET /api/settings.
func (c *Client) Settings(ctx context.Context) (model.Settings, error) {
	return api.Call[model.Settings](ctx, c.Transport, "GET", "/api/settings", nil, nil)
}

// Summary calls GET /api/summary.
func (c *Client) Summary(ctx context.Context) (model.Summary, error) {
	return api.Call[model.Summary](ctx, c.Transport, "GET", "/api/summary", nil, nil)
}

// Trace calls GET /api/traces/{id}.
func (c *Client) Trace(ctx context.Context, id string) (model.Trace, error) {
	return api.Call[model.Trace](ctx, c.Transport, "GET", api.Path("/api/traces/{id}", id), nil, nil)
}

// UpdateSettings calls PUT /api/settings.
func (c *Client) UpdateSettings(ctx context.Context, body model.Settings) (model.Settings, error) {
	return api.Call[model.Settings](ctx, c.Transport, "PUT", "/api/settings", nil, body)
}

// UpdateView calls PUT /api/views/{id}.
func (c *Client) UpdateView(ctx context.Context, id string, body model.View) (model.View, error) {
	return api.Call[model.View](ctx, c.Transport, "PUT", api.Path("/api/views/{id}", id), nil, body)
}

// ViewCatalogue calls GET /api/views/catalogue.
func (c *Client) ViewCatalogue(ctx context.Context) (contract.Catalogue, error) {
	return api.Call[contract.Catalogue](ctx, c.Transport, "GET", "/api/views/catalogue", nil, nil)
}

// ViewData calls GET /api/views/data.
func (c *Client) ViewData(ctx context.Context, query contract.ViewDataQuery) (model.Frame, error) {
	return api.Call[model.Frame](ctx, c.Transport, "GET", "/api/views/data", query, nil)
}

// Views calls GET /api/views.
func (c *Client) Views(ctx context.Context) ([]model.View, error) {
	return api.Call[[]model.View](ctx, c.Transport, "GET", "/api/views", nil, nil)
}

// WriteLog calls POST /api/logs.
func (c *Client) WriteLog(ctx context.Context, body contract.LogInput) (contract.Accepted, error) {
	return api.Call[contract.Accepted](ctx, c.Transport, "POST", "/api/logs", nil, body)
}
